version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - apt-add-repository ppa:ansible/ansible
      - apt-get update -y
      - apt-get install ansible -y 
      - npm install -g cfn-create-or-update
  pre_build:
    commands:
      - mkdir .ssh && aws s3 cp s3://$BUCKET/instance-need/.ssh/fiap-lab.pem .ssh/
  build:
    commands:
      - stackName="test-dev"
      - cfn-create-or-update --region us-east-1 --stack-name $stackName --wait --template-body file://ec2-cfn.yaml 
      - aws cloudformation --region us-east-1 describe-stacks --stack-name $stackName
      - publicIp=$(aws cloudformation --region us-east-1 describe-stacks --stack-name $stackName --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" --output text)
      - echo $publicIp
      - sed -i -e "s/PUBLIC_IP/$publicIp/g" hosts
      - cat hosts
      - export ANSIBLE_HOST_KEY_CHECKING=False
      - ansible all -m ping  -i hosts -u ubuntu
      - ansible-playbook -i hosts play.yaml 
      - echo "teste" >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt